version: "3"

services: 
  api-solid-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    volumes:
      - api_solid_volume:/bitnami/postgresql
volumes:
  api_solid_volume: